version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/application
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user

  # Download Bundle. Managed by AWS

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  #Installation step. Managed by AWS.

  AfterInstall:
    - location: scripts/docker_config.sh
      timeout: 900
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
