# This is experimental, don't use!
name: Deploy EC2 Instance

on: [push]

permissions:
      id-token: write
      contents: read  

jobs:
  aws-cdk-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "18.12.1"

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
        role-session-name: OIDCSession
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        npm install -g aws-cdk@2.50.0
        cdk --version
    
    - name: Deploy Stack
      run: cdk deploy --require-approval never --verbose
      working-directory: ./cdk
      env:
        AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_TAG_GROUP_NAME: ${{ secrets.AWS_TAG_GROUP_NAME }}
        AWS_TAG_NAME: ${{ secrets.AWS_TAG_NAME }}
        AWS_VPC_ID: ${{ secrets.VPC_ID }}
        AWS_KEY: ${{ secrets.AWS_KEY }}
        AWS_SG: ${{ secrets.AWS_SG }}
        AWS_NAME_INSTANCE: ${{ secrets.AWS_NAME_INSTANCE }}
