name: Delete resources

on:
   workflow_dispatch:


permissions:
  id-token: write
  contents: read
  
jobs:

  cdk-delete-resources:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      APP_NAME: ${{ secrets.APP_NAME }}
      ENVIRONMENT_DEPLOY: ${{ github.ref_name }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4.1.4

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE }}
        mask-aws-account-id: true
        role-duration-seconds: 600

    - name: Show Github actions custom variables
      run: |
        echo "Environment chosen: ${{ github.ref_name }}"

    - name: Delete stacks
      run: |
        stackNames=$(aws cloudformation list-stacks --query "StackSummaries[?starts_with(StackName, '${APP_NAME}-${ENVIRONMENT_DEPLOY}') && StackStatus=='CREATE_COMPLETE'].StackName" --output text)

        for stackName in $stackNames; do
          echo "Deleting stack: $stackName"
          aws cloudformation delete-stack --stack-name "$stackName"
        done
      
