name: Deploy resources

on:
   workflow_dispatch:
     inputs:
       reusableStack:
        type: choice
        description: 'Always detect changes between layers'
        options: 
        - True
        - False
        required: true
        default: False
       deployAplication:
        type: choice
        description: 'Deploy the application when creating the infrastructure'
        options: 
        - True
        - False
        required: true
        default: True

permissions:
  id-token: write
  contents: read

jobs:

  cdk-deploy-resources:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2
      
    - uses: actions/setup-node@v3
      with:
        node-version: "18.12.1"

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE }}
          
    - name: Install dependencies
      run: |
        pip install -r cdk/cdk_requirements.txt
        npm install -g aws-cdk
        # cdk --version

    - name: Show Github actions custom variables
      run: |
        echo "Reusable stacks: ${{ github.event.inputs.reusableStack }}"
        echo "Deploy app: ${{ github.event.inputs.deployAplication }}"
        echo "Environment chosen: ${{ github.ref_name }}"
    
    - name: Deploy stacks
      run: cdk deploy --app "python app.py" --require-approval never --all &> /dev/null
      working-directory: ./cdk
      env:
        REUSABLE_STACK: ${{ github.event.inputs.reusableStack }}
        ENVIRONMENT_DEPLOY: ${{ github.ref_name }}
        GENERIC_TZ: ${{ secrets.TZ }}
        # ------
        AWS_ROLE: ${{ secrets.AWS_ROLE }}
        AWS_SGPORTS: ${{ secrets.AWS_SGPORTS }}
        AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        # ------
        APP_NAME: ${{ secrets.APP_NAME }}

    - name: Deploy secrets
      run: aws secretsmanager put-secret-value --secret-id ${APP_NAME}-${ENVIRONMENT_DEPLOY}_secret1 --secret-string "{\"secret_telegram\":\"${TELEGRAM_TOKEN}\",\"secret_openai\":\"${OPENAI_TOKEN}\",\"secret_users\":\"${APP_USERSALLOWED}\",\"secret_admins\":\"${APP_ADMINSALLOWED}\"}" &> /dev/null

      env:
        APP_NAME: ${{ secrets.APP_NAME }}
        APP_USERSALLOWED: ${{ secrets.APP_USERSALLOWED }}
        APP_ADMINSALLOWED: ${{ secrets.APP_ADMINSALLOWED }}
        # ------
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        # ------
        ENVIRONMENT_DEPLOY: ${{ github.ref_name }}

        


  cdk-deploy-application:
    if: ${{ github.event.inputs.deployApplication }} == 'true'
    needs: cdk-deploy-resources
    uses: ./.github/workflows/update_application.yaml
    secrets: inherit
