# This is experimental, don't use!
name: Deploy application

on:
  push:
    branches:
      - "master"
      - "Dev"
  workflow_dispatch:
  workflow_call:

jobs:
  cdk-update-application:
    runs-on: ubuntu-latest
    environment: Development
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_TAG_NAME: ${{ secrets.AWS_TAG_NAME }}
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Compress Repository
      run: zip -r --exclude=*.git* --exclude=*/.* CompressedRepo-$GITHUB_RUN_NUMBER.zip .

    - name: Upload compressed file to S3
      id: tasks-s3
      run: |
        echo "BUCKETNAME=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'jepetobot')].Name" --output text)" >> $GITHUB_OUTPUT
        export BUCKETNAME=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'jepetobot')].Name" --output text)
        aws s3 cp CompressedRepo-$GITHUB_RUN_NUMBER.zip s3://$BUCKETNAME/ --region $AWS_REGION

    - name: Codedeploy execution
      run: |
        set +x

        export DEPLOYMENT_ID=$(aws deploy create-deployment --application-name $AWS_TAG_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name "$AWS_TAG_NAME-deploygroup" --s3-location bucket=${{ steps.tasks-s3.outputs.BUCKETNAME }},bundleType=zip,key=CompressedRepo-$GITHUB_RUN_NUMBER.zip --query deploymentId --output text)

        timeout 900s bash -c '
        while [ "$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query deploymentInfo.status --output text)" != "Succeeded" ]; do
          sleep 30
        done
        '
