# This is experimental, don't use!
name: Deploy Resources

on: push

jobs:
  aws-cdk-deploy:
    runs-on: ubuntu-latest
    environment: Development
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Compress Repository
      run: zip -r CompressedRepo.zip .

    - name: Upload compressed file to S3
      run: aws s3 cp CompressedRepo.zip s3://$AWS_BUCKET_NAME/ --region $AWS_REGION
      
    